### ISSUE TITLE
这是需要一个个填路径填文件名吗

### ISSUE THREAD

**Issue by RamenOfficial** [chrisis58/quick-linker#1]
有点麻烦啊

**Comment by chrisis58** [comment]
非常感谢你的反馈！

目前的版本中，源路径与目标路径需要手动填写，而剧集名称可以从路径中读取（父路径为季度编号，爷路径为剧集名称）。
在未来的版本中，可能会增加对上级目录的完整监听，从而达到只需要填写一次路径的功能。

另外的，本项目正在朝着命令行工具的形式进行重构（参考 dev 分支）。不过碍于前段时间精力有限，开发进度并不理想。
如果你对动画剧集自动下载并格式化有需求的话，可以参考 [Auto Bangumi](https://github.com/EstrellaXD/Auto_Bangumi) 项目。
